apiVersion: apps/v1
kind: Deployment
metadata:
  name: sorting-visualizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorting-visualizer
  template:
    metadata:
      labels:
        app: sorting-visualizer
    spec:
      containers:
      - name: sorting-visualizer
        image: sorting-visualizer:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
